create or replace table police_station(
ps_cd number(6,0) generated by default as identity,
ps_name varchar2(200),
state_cd number(2,0),
district_cd number(5,0),
place_of_ps varchar2(60),
modified_by varchar2(20),
modified_dttm datetime,
instantiated_by varchar2(20),
instantiated_dttm datetime,
validity_dttm datetime,
primary key (ps_cd)
);
create table state(
state_cd number(2,0),
state_name varchar2(100)
);
create table district(
district_cd number(5,0),
district_name varchar2(100),
state_cd number(2,0)
);
create table place(
place_of_ps varchar2(60),
district_cd number(5,0)
);
